project:
  type: website
  output-dir: report
  render:
    - index.qmd

resources:
  - resources/**
  - '!resources/1-essential/3-scripts/1-R/'
  - '!resources/1-essential/3-scripts/4-Python/'

format:
  html:
    css: resources/1-essential/3-scripts/3-CSS/styles.css
    theme: lux
    toc: false
    code-fold: false
    code-tools: false
    number-sections: false
    page-layout: custom
    smooth-scroll: true
    highlight-style: a11y-dark
    self-contained: false
    copy-files: true
    html: true

include-in-header:
  text: |-
    <link rel="shortcut icon" href="resources/1-essential/1-images/icono/favicon.svg"/>
    <link rel="icon" type="image/x-icon" href="resources/1-essential/1-images/icono/favicon.ico">

include-after-body:
  text: |-
    <script src="resources/1-essential/3-scripts/4-JS/chatbot.js"></script>

execute:
  echo: false
  warning: false
  message: false
  freeze: false
  cache: true

params:
  ruta_proyecto: ''
  tipo_analisis: ''

website:
  navbar:
    title: "<img class='brand-logo' src='/resources/1-essential/1-images/icono/ipbln_background.png'>
            <a class='brand-text' href='https://www.ipb.csic.es/servicios/Bioinformatica/index.html'>IPBLN</a>"
    right:
      - text: "Inicio"
        icon: house
        href: index.qmd
      - text: "Resumen 16S"
        icon: clipboard-data
        href: "resources/1-essential/3-scripts/2-Quarto/Tab2-Resumen/Tab2-1-Resumen-16S/resumen.qmd"
      - text: "Análisis 16S"
        icon: bar-chart
        menu:
          - text: ➤ Introducción contextual
            href: "resources/1-essential/3-scripts/2-Quarto/Tab3-Analisis/Tab3-1-Analisis-16S/0-contexto.qmd"
          - text: 1. Revisión inicial de muestras y metadatos
            href: "resources/1-essential/3-scripts/2-Quarto/Tab3-Analisis/Tab3-1-Analisis-16S/1-revision-inicial.qmd"
          - text: 2. Control de calidad y preprocesamiento
            href: "resources/1-essential/3-scripts/2-Quarto/Tab3-Analisis/Tab3-1-Analisis-16S/2-control-calidad.qmd"
          - text: 3. Generación de ASVs y tabla de abundancia
            href: "resources/1-essential/3-scripts/2-Quarto/Tab3-Analisis/Tab3-1-Analisis-16S/3-generacion-asvs.qmd"
          - text: 4. Asignación taxonómica y filogenia
            href: "resources/1-essential/3-scripts/2-Quarto/Tab3-Analisis/Tab3-1-Analisis-16S/4-taxonomia-filogenia.qmd"
          - text: 5. Análisis diferencial de abundancia
            href: "resources/1-essential/3-scripts/2-Quarto/Tab3-Analisis/Tab3-1-Analisis-16S/5-analisis-diferencial.qmd"
          - text: 6. Diversidad microbiana
            href: "resources/1-essential/3-scripts/2-Quarto/Tab3-Analisis/Tab3-1-Analisis-16S/6-diversidad-microbiana.qmd"
          - text: 7. Predicción funcional
            href: "resources/1-essential/3-scripts/2-Quarto/Tab3-Analisis/Tab3-1-Analisis-16S/7-prediccion-funcional.qmd"
          - text: 8. Conclusiones y perspectivas
            href: "resources/1-essential/3-scripts/2-Quarto/Tab3-Analisis/Tab3-1-Analisis-16S/8-conclusiones.qmd"
